language: java
jdk:
- oraclejdk7
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: R89ay/6L8wsuwkiuVAph1nFRhD07UEKcYGUGB09hQ6Ol89nLd0+yqflVs4tiYCv/4Rqd25uu+Qk64BvM5z3/Z3jqpy9R79q0R5JxUa1QUzCkzm23hTHEi0D6cgoQyOWT0ZClX0yW9pQum2tOxo9q0hHVJDjzDFpUnEJ0Z/SFjic=
  app: zebedee
  on:
    repo: davidcarboni/zebedee
after_deploy:
  - mvn -DbaseUrl=$BASE_URL clean test-compile failsafe:integration-test
