analysis :
  analyzer :
    #Overwriting default index analyzer
    #Makes all fields filterable with exact word matching, it is used to make filtering available on all fields by default
    #Searchable fields uses ons_analyzer
    default_index :
      type : custom
      tokenizer : keyword
      filter : [trim,lowercase]
    #ONS analyzer is used when indexing fields are wanted to be searchable, set mappings for these fields in default-mapping.json file
    ons_analyzer :
      tokenizer : standard
      filter : [standard, lowercase, stop, porter_stem]