---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java
    tag: 3.8.8-eclipse-temurin-8

inputs:
  - name: zebedee

outputs:
  - name: build

params:
  APPLICATION:

run:
  path: zebedee/ci/scripts/build.sh
